### ISSUE TITLE
Runtime high memory usage problem.

### ISSUE THREAD

**Issue by SkyWalker2506** [KhronosGroup/UnityGLTF#453]
Hi. I was using UniGltf but It was using too much memory so I decided to try this one. However results are much worse. After loading about 100 to 200 mb model for the UniGltf, It crashes. The memory limit of my device is 2800 mb. I haven't tried the limit of this one, since it already spent few times more memory. Most of the memory is spent on texture since it is decompressed it. Is there any way to make it spent less memory on runtime.

**Comment by AdamMitchell-ms** [comment]
Hi @SkyWalker2506,

Can you post the file that you are trying to load?  Your question is a bit broad, so I'm not sure how to address it without more details.

Does UnityGLTF consume all of the available RAM on the device and then it crashes?  In the current master, the process will be killed when it is out of memory.  I have a pull request out now (#454) that will throw an OutOfMemoryException and clean things up so that you can catch the exception and display a message to your user.  I'm not sure this will satisfy your needs.

**Comment by kevhane** [comment]
Hello, i think i have the same problem, i've got the following message when i try to import my file "file lengh does not match header".

**Comment by phanemy** [comment]
> Hi. I was using UniGltf but It was using too much memory so I decided to try this one. However results are much worse. After loading about 100 to 200 mb model for the UniGltf, It crashes. The memory limit of my device is 2800 mb. I haven't tried the limit of this one, since it already spent few times more memory. Most of the memory is spent on texture since it is decompressed it. Is there any way to make it spent less memory on runtime.

Theonly way i have find to bypass this problem is convert my gltf into asset (using gltfImporter, just drag and drop into editor) in that way unity will process texture and compress them  inn the right way, and the diference is huge(64Go+ to 4Go).

> Hello, i think i have the same problem, i've got the following message when i try to import my file "file lengh does not match header".

Your problem is something else, UnityGltf failed to load the model, it came from GLTFSceneImporter.cs in the method ConstructBufferFromGLB(int bufferIndex), it appear to be cause by the stream position alreadyto the end of the stream so the GLTFParser.SeekToBinaryChunk method failed, i fixed this by adding _gltfStream at the start of the method

**Comment by kevhane** [comment]
Hi Phanemy,
thanks a lot for your quick answer. I didn't really get your solution to fix my problem.
Is this what you mean ? 

_protected virtual BufferCacheData ConstructBufferFromGLB(int bufferIndex)
		{
			GLTFParser.SeekToBinaryChunk(_gltfStream.Stream, bufferIndex, _gltfStream.StartPosition);  // sets stream to correct start position
            return new BufferCacheData
            {   _gltfStream,
                Stream = _gltfStream.Stream,
				ChunkOffset = (uint)_gltfStream.Stream.Position
			};
		}_

**Comment by phanemy** [comment]
Hi, 
no i fixed like this
_gltfStream.StartPosition = 0;
 GLTFParser.SeekToBinaryChunk(_gltfStream.Stream, bufferIndex, _gltfStream.StartPosition);  // sets stream to correct start position
return new BufferCacheData
{
    Stream = _gltfStream.Stream,
    ChunkOffset = (uint)_gltfStream.Stream.Position
};

I hope this will work for you :)

**Comment by kevhane** [comment]
Hi,
I've done it but i still have a file lenght problem, i'm trying to import a .glb file wich is 9GB, is this not to much ? 

My error : 
Asset import failed, "Assets/67c11-000-000.glb" > GLTFHeaderInvalidException: File length does not match header.

GLTF.GLTFParser.ParseJsonChunk (System.IO.Stream stream, System.Int64 startPosition) (at <2f0dc9a61536460882b89b606e41e8d8>:0)
GLTF.GLTFParser.ParseJson (System.IO.Stream stream, GLTF.Schema.GLTFRoot& gltfRoot, System.Int64 startPosition) (at <2f0dc9a61536460882b89b606e41e8d8>:0)
UnityGLTF.GLTFImporter.CreateGLTFScene (System.String projectFilePath) (at Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs:341)
UnityGLTF.GLTFImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs:309)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at C:/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by AdamMitchell-ms** [comment]
@kevhane,
It sounds like your gltf/glb may be invalid.  Please test it with the [gltf validator](http://github.khronos.org/glTF-Validator/).  If it's invalid, then the fix is to correct the file.
But if the file is valid, then we should be able to load it and one of your proposed code changes may be the right fix.  If you do come up with a fix, please feel free to create a pull request with your fix.

Also, a 9GB file is pretty big.  Many devices will struggle to load such a model.  A very high end desktop may be able to handle it.

**Comment by kevhane** [comment]
Hi, thank you for your help, my file isn't valid. I have Chunk errors, textures errors, nodes errors ... Do you know how i can open the file to fix it ? ( wordpad doesn't work ) 

Also , does the following error mean my file is too big ? 

"code": "GLB_CHUNK_TOO_BIG",
                "message": "Chunk (0xb5beceb3) length (2881380837) does not fit total GLB length.",
                "severity": 0,
                "offset": 6833284145
Thanks a lot

**Comment by lexaknyazev** [comment]
This error means that a certain part of the GLB file is bigger than the file itself (as declared in the corresponding fields). Note, that GLB files cannot be bigger than 4GB because byte length fields are 32-bit.

**Comment by kevhane** [comment]
Ok thanks, i'm using XR exporter on solidworks 2019, it works well for smaller assembly. Do you know anything about it ?

**Comment by pfcDorn** [comment]
Please update to the latest version and open a new issue if the problem persists. Thanks!
