### ISSUE TITLE
GTLF importer doesn't set Root Motion to true when animation type is mecanim humanoid

### ISSUE THREAD

**Issue by XtroTheArctic** [KhronosGroup/UnityGLTF#867]
### Describe the bug 💬

This behavior is inconsistent with FBX importer and requires user to apply an prefab override manually on every single model imported.

FBX Importer:
![Image](https://github.com/user-attachments/assets/3c543910-188c-46e2-aca9-cb266448cb27)

UnityGLTF Importer:
![Image](https://github.com/user-attachments/assets/c804bcba-a5cc-41fc-b057-fbdf8ed3babd)

### Steps to reproduce 🔢

1. Import a model.
2. See that Root Motion  is unchecked.

### Editor Version 🎲

Other (Provide details below)

### Render Pipeline and version

Not relevant

### UnityGLTF Version

2.16.1

### Operating System 👩‍💻

Windows

### When does this problem happen?

- [x] Editor Import
- [ ] Runtime Import
- [ ] Editor Export
- [ ] Runtime Export

### Validations 🩹

- [x] I have [searched existing issues](https://github.com/KhronosGroup/UnityGLTF/issues): no issue already exist that reports the same problem.
- [x] I follow the [Code of Conduct](https://www.khronos.org/about/code-of-conduct)
- [x] I provided a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), including files when necessary.

**Comment by XtroTheArctic** [comment]
I'll send a PR for this hopefully soon.

**Comment by hybridherbst** [comment]
Fixed in 2.17.0. Thanks!

**Comment by XtroTheArctic** [comment]
Thank you. I'll test it.

About your comment in PR:
"Unity does not generate an Animator for objects without animations that have animation mode set to "Generic", so I removed removed the part again that enables root motion for non-humanoid mecanim animations."

I think I tested this before making the change for "generic" but I'll check it again.

**Comment by XtroTheArctic** [comment]
I tested this and it works fine for "mecanim humanoid". Thank you for the merge.

For "Mecanim" animation type, I checked and saw that my earlier test was correct so, this is still an issue. I created a separate issue and I'll submit a PR soon.
https://github.com/KhronosGroup/UnityGLTF/issues/869
